apiVersion: aquasecurity.github.io/v1alpha1
kind: ClusterComplianceReport
metadata:
  labels:
    battery/app: trivy-operator
  name: nsa
spec:
  compliance:
    controls:
      - checks:
          - id: AVD-KSV-0012
        description: Check that container is not running as root
        id: '1.0'
        name: Non-root containers
        severity: MEDIUM
      - checks:
          - id: AVD-KSV-0014
        description: Check that container root file system is immutable
        id: '1.1'
        name: Immutable container file systems
        severity: LOW
      - checks:
          - id: AVD-KSV-0017
        description: Controls whether Pods can run privileged containers
        id: '1.2'
        name: Preventing privileged containers
        severity: HIGH
      - checks:
          - id: AVD-KSV-0008
        description: Controls whether containers can share process namespaces
        id: '1.3'
        name: Share containers process namespaces
        severity: HIGH
      - checks:
          - id: AVD-KSV-0009
        description: Controls whether share host process namespaces
        id: '1.4'
        name: Share host process namespaces
        severity: HIGH
      - checks:
          - id: AVD-KSV-0010
        description: Controls whether containers can use the host network
        id: '1.5'
        name: Use the host network
        severity: HIGH
      - checks:
          - id: AVD-KSV-0029
        description: Controls whether container applications can run with root privileges or with root group membership
        id: '1.6'
        name: Run with root privileges or with root group membership
        severity: LOW
      - checks:
          - id: AVD-KSV-0001
        description: Control check restrictions escalation to root privileges
        id: '1.7'
        name: Restricts escalation to root privileges
        severity: MEDIUM
      - checks:
          - id: AVD-KSV-0002
        description: Control checks if pod sets the SELinux context of the container
        id: '1.8'
        name: Sets the SELinux context of the container
        severity: MEDIUM
      - checks:
          - id: AVD-KSV-0030
        description: Control checks the restriction of containers access to resources with AppArmor
        id: '1.9'
        name: Restrict a container's access to resources with AppArmor
        severity: MEDIUM
      - checks:
          - id: AVD-KSV-0030
        description: Control checks the sets the seccomp profile used to sandbox containers
        id: '1.10'
        name: Sets the seccomp profile used to sandbox containers.
        severity: LOW
      - checks:
          - id: AVD-KSV-0036
        description: 'Control check whether disable secret token been mount ,automountServiceAccountToken: false'
        id: '1.11'
        name: Protecting Pod service account tokens
        severity: MEDIUM
      - checks:
          - id: AVD-KSV-0037
        defaultStatus: FAIL
        description: Control check whether Namespace kube-system is not be used by users
        id: '1.12'
        name: Namespace kube-system should not be used by users
        severity: MEDIUM
      - checks:
          - id: AVD-KSV-0038
        defaultStatus: FAIL
        description: Control check validate the pod and/or namespace Selectors usage
        id: '2.0'
        name: Pod and/or namespace Selectors usage
        severity: MEDIUM
      - checks:
        defaultStatus: FAIL
        description: Control check whether check cni plugin installed
        id: '3.0'
        name: Use CNI plugin that supports NetworkPolicy API (Manual)
        severity: CRITICAL
      - checks:
          - id: AVD-KSV-0040
        defaultStatus: FAIL
        description: Control check the use of ResourceQuota policy to limit aggregate resource usage within namespace
        id: '4.0'
        name: Use ResourceQuota policies to limit resources
        severity: MEDIUM
      - checks:
          - id: AVD-KSV-0039
        defaultStatus: FAIL
        description: Control check the use of LimitRange policy limit resource usage for namespaces or nodes
        id: '4.1'
        name: Use LimitRange policies to limit resources
        severity: MEDIUM
      - checks:
        defaultStatus: FAIL
        description: Control check whether control plan disable insecure port
        id: '5.0'
        name: Control plan disable insecure port (Manual)
        severity: CRITICAL
      - checks:
          - id: AVD-KCV-0030
        description: Control check whether etcd communication is encrypted
        id: '5.1'
        name: Encrypt etcd communication
        severity: CRITICAL
      - checks:
        defaultStatus: FAIL
        description: Control check whether kube config file permissions
        id: '6.0'
        name: Ensure kube config file permission (Manual)
        severity: CRITICAL
      - checks:
          - id: AVD-KCV-0029
        description: Control checks whether encryption resource has been set
        id: '6.1'
        name: Check that encryption resource has been set
        severity: CRITICAL
      - checks:
          - id: AVD-KCV-0004
        description: Control checks whether encryption provider has been set
        id: '6.2'
        name: Check encryption provider
        severity: CRITICAL
      - checks:
          - id: AVD-KCV-0001
        description: Control checks whether anonymous-auth is unset
        id: '7.0'
        name: Make sure anonymous-auth is unset
        severity: CRITICAL
      - checks:
          - id: AVD-KCV-0008
        description: Control check whether RBAC permission is in use
        id: '7.1'
        name: Make sure -authorization-mode=RBAC
        severity: CRITICAL
      - checks:
        defaultStatus: FAIL
        description: Control check whether audit policy is configure
        id: '8.0'
        name: Audit policy is configure (Manual)
        severity: HIGH
      - checks:
          - id: AVD-KCV-0019
        description: Control check whether audit log path is configure
        id: '8.1'
        name: Audit log path is configure
        severity: MEDIUM
      - checks:
          - id: AVD-KCV-0020
        description: Control check whether audit log aging is configure
        id: '8.2'
        name: Audit log aging
        severity: MEDIUM
    description: National Security Agency - Kubernetes Hardening Guidance
    id: nsa
    relatedResources:
      - https://www.nsa.gov/Press-Room/News-Highlights/Article/Article/2716980/nsa-cisa-release-kubernetes-hardening-guidance/
    title: National Security Agency - Kubernetes Hardening Guidance v1.0
    version: '1.0'
  cron: 0 */6 * * *
  reportType: summary
