name: BI Cli

on:
  push:
    branches:
      - master
      - gh-readonly-queue/master/**
  pull_request:
    branches:
      - master

jobs:
  bi:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: batteries-included
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush:
            ${{ !(github.ref == 'refs/heads/master' && github.event_name ==
            'push') }}
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v6
      - run: nix build .#bi -L

  bi-int-test:
    runs-on: ubuntu-latest
    needs: bi
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v14
        with:
          name: batteries-included
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush:
            ${{ !(github.ref == 'refs/heads/master' && github.event_name ==
            'push') }}
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v6
      - name: Run integration tests
        run: nix develop --command bash -c "TRACE=1 INTEGRATION=1 bix go-test"
