---
name: Manage Caches

'on':
  push:
    branches:
      - master

env:
  GOCACHE: ${{ vars.GOCACHE }}
  GOMODCACHE: ${{ vars.GOMODCACHE }}
  ASDF_PATHS: |
    ~/.asdf/installs
    ~/.asdf/plugins
    ~/.asdf/shims
  ELIXIR_PATHS: |
    platform_umbrella/deps
    platform_umbrella/_build
    platform_umbrella/.dialyzer
  GO_PATHS: |
    ${{ vars.GOCACHE }}
    ${{ vars.GOMODCACHE }}
  BI_PATHS: |
    /home/runner/.local/share/bi/dev/
  REG_TOOL_PATHS: |
    /home/runner/.local/share/bi/registry-tool/
  IMAGE_PATHS: |
    /home/runner/work/_temp/base_images.tar

defaults:
  run:
    shell: bash

jobs:
  check-caches:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v4
        with:
          persist-credentials: false

      - name: Compute hash keys
        env:
          ASDF_HASH_KEY:
            ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
          ELIXIR_HASH_KEY:
            ${{ runner.os }}-ex-${{ hashFiles('**/mix.lock', '.tool-versions')
            }}
          GO_HASH_KEY:
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum', '.tool-versions') }}
          IMAGE_HASH_KEY:
            ${{ runner.os }}-images-${{ hashFiles('image_registry.yaml')}}

        run: |
          bi_rev="$(bin/bix go bi-revision)"
          BI_HASH_KEY="${{ runner.os }}-bi-${bi_rev}"
          reg_tool_rev="$(bin/bix go registry-tool-revision)"
          REG_TOOL_HASH_KEY="${{ runner.os }}-reg-tool-${reg_tool_rev}"

          {
            echo "ASDF_HASH_KEY=$ASDF_HASH_KEY";
            echo "ELIXIR_HASH_KEY=$ELIXIR_HASH_KEY";
            # shellcheck disable=SC2153
            echo "GO_HASH_KEY=$GO_HASH_KEY";
            echo "BI_HASH_KEY=$BI_HASH_KEY";
            echo "REG_TOOL_HASH_KEY=$REG_TOOL_HASH_KEY";
            echo "IMAGE_HASH_KEY=$IMAGE_HASH_KEY";
          } >> "$GITHUB_ENV"

      - name: Check existing ASDF cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: asdf
        with:
          path: ${{ env.ASDF_PATHS }}
          key: ${{ env.ASDF_HASH_KEY }}
          lookup-only: true

      - name: Check existing elixir cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: elixir
        with:
          path: ${{ env.ELIXIR_PATHS }}
          key: ${{ env.ELIXIR_HASH_KEY }}
          lookup-only: true

      - name: Check existing Go cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: go
        with:
          path: ${{ env.GO_PATHS }}
          key: ${{ env.GO_HASH_KEY }}
          lookup-only: true

      - name: Check existing bi cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: bi
        with:
          path: ${{ env.BI_PATHS }}
          key: ${{ env.BI_HASH_KEY }}
          lookup-only: true

      - name: Check existing registry tool cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: reg-tool
        with:
          path: ${{ env.REG_TOOL_PATHS }}
          key: ${{ env.REG_TOOL_HASH_KEY }}
          lookup-only: true

      - name: Check existing image cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: images
        with:
          path: ${{ env.IMAGE_PATHS }}
          key: ${{ env.IMAGE_HASH_KEY }}
          lookup-only: true

    outputs:
      asdf-cache-hit: ${{ steps.asdf.outputs.cache-hit }}
      asdf-hash-key: ${{ env.ASDF_HASH_KEY }}
      elixir-cache-hit: ${{ steps.elixir.outputs.cache-hit }}
      elixir-hash-key: ${{ env.ELIXIR_HASH_KEY }}
      go-cache-hit: ${{ steps.go.outputs.cache-hit }}
      go-hash-key: ${{ env.GO_HASH_KEY }}
      bi-cache-hit: ${{ steps.bi.outputs.cache-hit }}
      bi-hash-key: ${{ env.BI_HASH_KEY }}
      reg-tool-cache-hit: ${{ steps.reg-tool.outputs.cache-hit }}
      reg-tool-hash-key: ${{ env.REG_TOOL_HASH_KEY }}
      image-cache-hit: ${{ steps.images.outputs.cache-hit }}
      image-hash-key: ${{ env.IMAGE_HASH_KEY }}

  cache-asdf:
    # ASDF tool-versions changed, install and re-cache
    if: ${{ ! (needs.check-caches.outputs.asdf-cache-hit) }}
    needs: check-caches
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v4
        with:
          persist-credentials: false

      - name: Install ASDF Tools
        uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4
        with:
          asdf_version: '0.18.0'

      - name: Reshim ASDF
        run: asdf reshim

      - name: Save ASDF cache
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ${{ env.ASDF_PATHS }}
          key: ${{ needs.check-caches.outputs.asdf-hash-key }}

  cache-elixir:
    # elixir deps changed, re-cache
    if: ${{ ! (needs.check-caches.outputs.elixir-cache-hit) }}
    needs: check-caches
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v4
        with:
          persist-credentials: false

      - name: Setup ASDF
        uses: ./.github/actions/setup-asdf

      - name: Compile with dependencies
        env:
          MIX_ENV: test
        run: bin/bix mix "do" deps.get, compile --force

      - name: Build PLTs
        run: bin/bix mix dialyzer --plt

      - name: Save Elixir cache
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: elixir-cache
        with:
          path: ${{ env.ELIXIR_PATHS }}
          key: ${{ needs.check-caches.outputs.elixir-hash-key }}

  cache-go:
    # go deps changed, re-cache
    if: ${{ ! (needs.check-caches.outputs.go-cache-hit) }}
    needs: check-caches
    runs-on: ubuntu-latest-m
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v4
        with:
          persist-credentials: false

      - name: Setup ASDF
        uses: ./.github/actions/setup-asdf

      - name: Build `bi` for caching
        run: bin/bix go bi-snapshot-release

      - name: Test for caching
        run: bin/bix go test

      - name: Save Go cache
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: go-cache
        with:
          path: ${{ env.GO_PATHS }}
          key: ${{ needs.check-caches.outputs.go-hash-key }}

  cache-bi:
    if: ${{ ! (needs.check-caches.outputs.bi-cache-hit) }}
    needs: check-caches
    runs-on: ubuntu-latest-m
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v4
        with:
          persist-credentials: false

      # pull whatever go cache we have to build the bi binary
      - name: Setup CI
        uses: ./.github/actions/setup-ci
        with:
          elixir_cache: false

      - name: Build `bi` for caching
        run: bin/bix go ensure-bi

      - name: Save `bi` cache
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: bi-cache
        with:
          path: |
            /home/runner/.local/share/bi/dev/
          key: ${{ needs.check-caches.outputs.bi-hash-key }}

  cache-registry-tool:
    if: ${{ ! (needs.check-caches.outputs.reg-tool-cache-hit) }}
    needs: check-caches
    runs-on: ubuntu-latest-m
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v4
        with:
          persist-credentials: false

      # pull whatever go cache we have to build the bi binary
      - name: Setup CI
        uses: ./.github/actions/setup-ci
        with:
          elixir_cache: false

      - name: Build `registry-tool` for caching
        run: bin/bix go ensure-registry-tool

      - name: Save `registry-tool` cache
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: registry-tool-cache
        with:
          path: |
            /home/runner/.local/share/bi/registry-tool/
          key: ${{ needs.check-caches.outputs.reg-tool-hash-key }}

  cache-images:
    if: ${{ ! (needs.check-caches.outputs.image-cache-hit) }}
    needs: check-caches
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # we'll want to pull existing base images if possible
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v4
        with:
          persist-credentials: false

      - name: Setup ASDF
        uses: ./.github/actions/setup-asdf

      - name: Login to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create image archive
        run: |
          bin/bix \
            registry \
            save-bootstrap-images-from-registry \
            /home/runner/work/_temp/base_images.tar

      - name: Save images cache
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: images-cache
        with:
          path: ${{ env.IMAGE_PATHS }}
          key: ${{ needs.check-caches.outputs.image-hash-key }}
