---
name: 'Trigger Missing Images From Upstream'

'on':
  schedule:
    - cron: '15 8 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  check_upstream:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        target:
          - keycloak
          - postgres
          - deploy-base
          - build-base

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v4
        with:
          persist-credentials: false

      - name: Setup ASDF
        uses: ./.github/actions/setup-asdf

      - name: Find missing tags and kick off build & push workflow
        env:
          GH_TOKEN: ${{ github.token }}
        run: bin/bix docker trigger-missing-upstream ${{ matrix.target }}
