name: Platform Umbrella

on:
  push:
    branches:
      - master
      - gh-readonly-queue/master/**
  pull_request:
    branches:
      - master

jobs:
  int-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: battery-local-user
          POSTGRES_PASSWORD: 'batterypasswd'
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports: ['5432:5432']
    env:
      POSTGRES_HOST: localhost
      POSTGRES_USER: battery-local-user
      POSTGRES_PASSWORD: 'batterypasswd'
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v15
        with:
          name: batteries-included
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush:
            ${{ !(github.ref == 'refs/heads/master' && github.event_name ==
            'push') }}
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v6
      - name: Set up dev shell
        run: nix develop --command bash -c 'exit 0'
      - name: Start Kind
        run: nix develop --command bash -c "bi -v=debug start ./bootstrap/integration-test.spec.json"
      - name: Run integration tests
        run: nix develop --command bash -c "TRACE=1 bix ex-int-test"
      - name: Stop Kind
        run: nix develop --command bash -c "TRACE=1 bix stop ./bootstrap/integration-test.spec.json"
      - name: Save screenshots as artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: wallaby-screenshots
          path: |
            platform_umbrella/apps/control_server_web/screenshots
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: ${{github.actor != 'dependabot[bot]' &&  (success() || failure())}}
        with:
          name: Mix Integration Test Results
          path: platform_umbrella/_build/**/test-junit-report.xml
          reporter: java-junit
  platform-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: battery-local-user
          POSTGRES_PASSWORD: 'batterypasswd'
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports: ['5432:5432']
    env:
      POSTGRES_HOST: localhost
      POSTGRES_USER: battery-local-user
      POSTGRES_PASSWORD: 'batterypasswd'
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v15
        with:
          name: batteries-included
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush:
            ${{ !(github.ref == 'refs/heads/master' && github.event_name ==
            'push') }}
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v6
      - run: nix develop --command bash bix ex-test-deep
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: ${{github.actor != 'dependabot[bot]' &&  (success() || failure())}}
        with:
          name: Mix Test Results
          path: platform_umbrella/_build/**/test-junit-report.xml
          reporter: java-junit
